title: typetune
description: "A blog exploring typography used in music "
header_text: Where words fail, music speaks
footer_text: Copyright 2020 Laura Cutting
header_feature_image: ../uploads/jack-hamilton-cmnniqbkwbi-unsplash.jpg
bannerheight: 20vmax
logo: ../uploads/logo-2.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
