title: typetune
description: "A blog exploring typography used in music "
header_text: where words fail, music speaks
footer_text: Copyright 2020 Laura Cutting
header_feature_image: ../uploads/strip.png
bannerheight: 20vmax
logo: ../uploads/logo-2-1-.png
favicon: ../uploads/logo-2-1-.png
gridlayout: true
fixednavbar: true
upzoom: true
